apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: pipelinerun-blue-green-1
spec:
  serviceAccountName: tekton-blue-green
  pipelineRef:
    name: tekton-blue-green-1
  resources:
    - name: source-repo
      resourceRef:
        name: tekton-helloworld-git
