apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: task-with-parameters
spec:
  inputs:
    params:
      - name: flags
        type: array
      - name: someURL
        type: string
  steps:
    - name: build
      #image: registry.cn-hangzhou.aliyuncs.com/knative-sample/alpine:3.9
      image: busybox
      command: ["sh", "-c"]
      args: [ "echo ${flags}; echo ${someURL}"]
